CREATE TABLE IF NOT EXISTS Sync_Work_Config_table (
    id                      BIGINT AUTO_INCREMENT PRIMARY KEY,
    name                    VARCHAR(128) NOT NULL,
    description             VARCHAR(255),
    createdDate             TIMESTAMP,
    encryptionKey           VARCHAR(255),
    srcRepoPluginName       VARCHAR(255),
    syncToRepoCron          VARCHAR(255),
    syncToRepoEnabled       BOOLEAN      NOT NULL,
    syncToServerEnabled     BOOLEAN      NOT NULL,
    syncToZanataCron        VARCHAR(255),
    syncToZanataOption      VARCHAR(255),
    zanataUsername          VARCHAR(255) NOT NULL,
    zanataSecret            VARCHAR(255) NOT NULL,
    zanataServerUrl         VARCHAR(255) NOT NULL,
    srcRepoUrl              VARCHAR(255) NOT NULL,
    srcRepoUsername         VARCHAR(255) NOT NULL,
    srcRepoSecret           VARCHAR(255) NOT NULL,
    srcRepoBranch           VARCHAR(255) NOT NULL,
    INDEX config_name_idx (name),
    INDEX config_zanata_username_idx (zanataUsername)
)
    ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS Job_Status_table (
    id            VARCHAR(255) PRIMARY KEY,
    workId        BIGINT      NOT NULL,
    jobType       VARCHAR(20) NOT NULL,
    status        VARCHAR(20) NOT NULL,
    startTime     TIMESTAMP,
    endTime       TIMESTAMP,
    nextStartTime TIMESTAMP,
    INDEX job_status_work_id_idx (workId),
    INDEX job_status_work_type_idx (workId, jobType),
    INDEX job_status_id_idx (id),
    INDEX job_status_end_time_idx (endTime),
    FOREIGN KEY (workId) REFERENCES Sync_Work_Config_table (id)
        ON DELETE CASCADE
)
    ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS System_Settings_table (
    id           BIGINT AUTO_INCREMENT PRIMARY KEY,
    version      BIGINT      NOT NULL,
    settingKey   VARCHAR(50) NOT NULL UNIQUE,
    settingValue VARCHAR(50) NOT NULL,
    INDEX setting_key_idx (settingKey)
)
    ENGINE = InnoDB;

-- generated by default as identity