CREATE TABLE IF NOT EXISTS ZanataAccount (
    id            BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    localUsername VARCHAR(255),
    secret        VARCHAR(255),
    server        VARCHAR(255),
    username      VARCHAR(255),
    INDEX zanata_account_idx (server, username),
    UNIQUE zanata_account_UK (server, username)
)
    ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS RepoAccount (
    id            BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    repoHostname  VARCHAR(255) NOT NULL,
    repoType      VARCHAR(255) NOT NULL,
    secret        VARCHAR(255),
    username      VARCHAR(255),
    zanataAccount BIGINT NOT NULL,
    UNIQUE repo_account_UK (repoHostname, username),
    INDEX repo_account_natural_key_idx (repoHostname, username),
    INDEX repo_account_zanata_account_idx (zanataAccount),
    FOREIGN KEY repo_account_zanata_account_fk (zanataAccount) REFERENCES ZanataAccount (id)
)
    ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS Sync_Work_Config_table (
    id                  BIGINT AUTO_INCREMENT PRIMARY KEY,
    name                VARCHAR(128) NOT NULL,
    description         VARCHAR(255),
    createdDate         TIMESTAMP,
    syncToRepoCron      VARCHAR(255),
    syncToRepoEnabled   BOOLEAN      NOT NULL,
    syncToServerEnabled BOOLEAN      NOT NULL,
    syncToZanataCron    VARCHAR(255),
    syncToZanataOption  VARCHAR(255),
    repoAccount         BIGINT       NOT NULL,
    zanataAccount       BIGINT       NOT NULL,
    srcRepoUrl          VARCHAR(255) NOT NULL,
    srcRepoBranch       VARCHAR(255) NOT NULL,
    INDEX config_name_idx (name),
    INDEX config_repo_account_idx (repoAccount),
    INDEX config_zanata_account_idx (zanataAccount),
    FOREIGN KEY config_repo_account_fk (repoAccount) REFERENCES RepoAccount (id),
    FOREIGN KEY config_zanata_account_fk (zanataAccount) REFERENCES ZanataAccount (id)
)
    ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS Job_Status_table (
    id            VARCHAR(255) PRIMARY KEY,
    workId        BIGINT      NOT NULL,
    jobType       VARCHAR(20) NOT NULL,
    status        VARCHAR(20) NOT NULL,
    startTime     TIMESTAMP,
    endTime       TIMESTAMP,
    nextStartTime TIMESTAMP,
    INDEX job_status_work_id_idx (workId),
    INDEX job_status_work_type_idx (workId, jobType),
    INDEX job_status_id_idx (id),
    INDEX job_status_end_time_idx (endTime),
    FOREIGN KEY (workId) REFERENCES Sync_Work_Config_table (id)
        ON DELETE CASCADE
)
    ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS System_Settings_table (
    id           BIGINT AUTO_INCREMENT PRIMARY KEY,
    version      BIGINT      NOT NULL,
    settingKey   VARCHAR(50) NOT NULL UNIQUE,
    settingValue VARCHAR(50) NOT NULL,
    INDEX setting_key_idx (settingKey)
)
    ENGINE = InnoDB;

-- generated by default as identity